set_attribute -type boolean [get_pins memForAorB_1\/ram1rw_4\/ram/CLK] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[3]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[4]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[5]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[6]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[7]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[8]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[9]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[10]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[11]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[12]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[13]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[14]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[15]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[1]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[2]] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/CLK] is_pad true
set_attribute -type boolean [get_pins memForWeight_1\/ram1rw_4\/ram/D[0]] is_pad true
set_attribute -type boolean [get_pins memForAorB_0\/ram1rw_4\/ram/CLK] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[3]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[4]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[5]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[6]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[7]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[8]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[9]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[10]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[11]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[12]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[13]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[14]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[15]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[1]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[2]] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/CLK] is_pad true
set_attribute -type boolean [get_pins memForWeight_0\/ram1rw_4\/ram/D[0]] is_pad true
